name: React CI with Docker, Tests, and ECR

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Docker Version and Features
        run: |
          docker --version
          docker build --help

      - name: Build test image
        run: |
          docker build --target test -t test-image:latest .

      - name: Run tests inside Docker container
        run: docker run test-image:latest npm test --watchAll=false

      - name: Build production image
        run: |
          docker build --target 2 -t production-image:latest .

      - name: Configure AWS credentials using the AWS CLI action
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr_loginui
        uses: aws-actions/amazon-ecr-login@v1

      - name: Debug - Check AWS account ID and region
        run: |
          echo "Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "Region: ${{ secrets.AWS_REGION }}"

      - name: Tag Docker image
        run: |
          docker tag production-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/comet-app-repo:react-latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/comet-app-repo:react-latest